package com.tincio.visualizarboletas.data.services;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.8.1
//
// Created by Quasar Development at 20/09/2016
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.math.BigDecimal;

public class CULDocumentoDetalle extends AttributeContainer implements KvmSerializable
{

    
    public CULDocumento documento;
    
    public Long idCabeceraDetalle;
    
    public String indMesAFP;
    
    public CULSeccion seccion;
    
    public BigDecimal valorColumna;

    public CULDocumentoDetalle ()
    {
    }

    public CULDocumentoDetalle (Object paramObj,CULExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                Object obj = info.getValue();
                if (info.name.equals("documento"))
                {
                    if(obj!=null)
                    {
                        Object j = obj;
                        this.documento = (CULDocumento)__envelope.get(j,CULDocumento.class);
                    }
                    continue;
                }
                if (info.name.equals("idCabeceraDetalle"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.idCabeceraDetalle = new Long(j.toString());
                            }
                        }
                        else if (obj instanceof Long){
                            this.idCabeceraDetalle = (Long)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("indMesAFP"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.indMesAFP = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.indMesAFP = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("seccion"))
                {
                    if(obj!=null)
                    {
                        Object j = obj;
                        this.seccion = (CULSeccion)__envelope.get(j,CULSeccion.class);
                    }
                    continue;
                }
                if (info.name.equals("valorColumna"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.valorColumna = new BigDecimal(j.toString());
                            }
                        }
                        else if (obj instanceof BigDecimal){
                            this.valorColumna = (BigDecimal)obj;
                        }
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.documento!=null?this.documento:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.idCabeceraDetalle!=null?this.idCabeceraDetalle:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.indMesAFP!=null?this.indMesAFP:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.seccion!=null?this.seccion:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.valorColumna!=null?this.valorColumna.toString():SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 5;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = CULDocumento.class;
            info.name = "documento";
            info.namespace= "http://entity.sibe.gmd.com.pe/xsd";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "idCabeceraDetalle";
            info.namespace= "http://entity.sibe.gmd.com.pe/xsd";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "indMesAFP";
            info.namespace= "http://entity.sibe.gmd.com.pe/xsd";
        }
        if(propertyIndex==3)
        {
            info.type = CULSeccion.class;
            info.name = "seccion";
            info.namespace= "http://entity.sibe.gmd.com.pe/xsd";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "valorColumna";
            info.namespace= "http://entity.sibe.gmd.com.pe/xsd";
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

}
