package com.tincio.visualizarboletas.data.services;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.8.1
//
// Created by Quasar Development at 20/09/2016
//
//---------------------------------------------------



public interface CULIServiceEvents
{
    public void Starting();
    public void Completed(CULOperationResult result);
}
