package com.tincio.visualizarboletas.data.services;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.8.1
//
// Created by Quasar Development at 20/09/2016
//
//---------------------------------------------------



public class CULOperationResult< T>
{
    public java.lang.Exception Exception;
    public T Result;
    public Object Tag;
    public String MethodName;
}
