package com.tincio.visualizarboletas.data.services;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.8.1
//
// Created by Quasar Development at 20/09/2016
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class CULTipoDocumental extends AttributeContainer implements KvmSerializable
{

    
    public String descripcion;
    
    public Integer estado;
    
    public Integer idTipoDocumental;
    
    public String planTipo;

    public CULTipoDocumental ()
    {
    }

    public CULTipoDocumental (Object paramObj,CULExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                Object obj = info.getValue();
                if (info.name.equals("descripcion"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.descripcion = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.descripcion = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("estado"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.estado = Integer.parseInt(j.toString());
                            }
                        }
                        else if (obj instanceof Integer){
                            this.estado = (Integer)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("idTipoDocumental"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.idTipoDocumental = Integer.parseInt(j.toString());
                            }
                        }
                        else if (obj instanceof Integer){
                            this.idTipoDocumental = (Integer)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("planTipo"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.planTipo = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.planTipo = (String)obj;
                        }
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.descripcion!=null?this.descripcion:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.estado!=null?this.estado:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.idTipoDocumental!=null?this.idTipoDocumental:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.planTipo!=null?this.planTipo:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 4;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "descripcion";
            info.namespace= "http://entity.sibe.gmd.com.pe/xsd";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "estado";
            info.namespace= "http://entity.sibe.gmd.com.pe/xsd";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "idTipoDocumental";
            info.namespace= "http://entity.sibe.gmd.com.pe/xsd";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "planTipo";
            info.namespace= "http://entity.sibe.gmd.com.pe/xsd";
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

}
