package com.tincio.visualizarboletas.data.services;




//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.8.1
//
// Created by Quasar Development at 20/09/2016
//
//---------------------------------------------------




import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.*;
import org.ksoap2.transport.*;
import org.kxml2.kdom.Element;

import java.lang.reflect.Constructor;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


public class CULWSAutenticacionSoap11Binding
{
    interface CULIWcfMethod
    {
        CULExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws Exception;

        Object ProcessResult(CULExtendedSoapSerializationEnvelope __envelope, Object result) throws Exception;
    }

    String url="http://200.41.98.10:8080/wsDocuServices/services/WSAutenticacion.WSAutenticacionHttpSoap11Endpoint/";

    int timeOut=60000;
    public List< HeaderProperty> httpHeaders;
    public boolean enableLogging;

    CULIServiceEvents callback;
    public CULWSAutenticacionSoap11Binding(){}

    public CULWSAutenticacionSoap11Binding (CULIServiceEvents callback)
    {
        this.callback = callback;
    }
    public CULWSAutenticacionSoap11Binding(CULIServiceEvents callback,String url)
    {
        this.callback = callback;
        this.url = url;
    }

    public CULWSAutenticacionSoap11Binding(CULIServiceEvents callback,String url,int timeOut)
    {
        this.callback = callback;
        this.url = url;
        this.timeOut=timeOut;
    }

    protected Transport createTransport()
    {
        try
        {
            java.net.URI uri = new java.net.URI(url);
            if(uri.getScheme().equalsIgnoreCase("https"))
            {
                int port=uri.getPort()>0?uri.getPort():443;
                return new HttpsTransportSE(uri.getHost(), port, uri.getPath(), timeOut);
            }
            else
            {
                return new HttpTransportSE(url,timeOut);
            }

        }
        catch (java.net.URISyntaxException e)
        {
        }
        return null;
    }
    
    protected CULExtendedSoapSerializationEnvelope createEnvelope()
    {
        CULExtendedSoapSerializationEnvelope envelope= new CULExtendedSoapSerializationEnvelope(CULExtendedSoapSerializationEnvelope.VER11);
        return envelope;
    }
    
    protected List sendRequest(String methodName,CULExtendedSoapSerializationEnvelope envelope,Transport transport  )throws Exception
    {
        return transport.call(methodName, envelope, httpHeaders);
    }

    Object getResult(Class destObj,Object source,String resultName,CULExtendedSoapSerializationEnvelope __envelope) throws Exception
    {
        if(source==null)
        {
            return null;
        }
        if(source instanceof SoapPrimitive)
        {
            SoapPrimitive soap =(SoapPrimitive)source;
            if(soap.getName().equals(resultName))
            {
                Object instance=__envelope.get(source,destObj);
                return instance;
            }
        }
        else
        {
            SoapObject soap = (SoapObject)source;
            if (soap.hasProperty(resultName))
            {
                Object j=soap.getProperty(resultName);
                if(j==null)
                {
                    return null;
                }
                Object instance=__envelope.get(j,destObj);
                return instance;
            }
            else if( soap.getName().equals(resultName)) {
                Object instance=__envelope.get(source,destObj);
                return instance;
            }
       }

       return null;
    }

        
    public CULgetListadoDocumentosNoRevisadosResponse getListadoDocumentosNoRevisados(final Integer codAplicacion,final Integer idEmpresa,final String nroDocumentoIdentificacion,final String idTipoDocumento ) throws Exception
    {
        return (CULgetListadoDocumentosNoRevisadosResponse)execute(new CULIWcfMethod()
        {
            @Override
            public CULExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              CULExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://wsdocuservutil.gmd.com.pe", "getListadoDocumentosNoRevisados");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="codAplicacion";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(codAplicacion);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="idEmpresa";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(idEmpresa);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="nroDocumentoIdentificacion";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(nroDocumentoIdentificacion!=null?nroDocumentoIdentificacion:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="idTipoDocumento";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(idTipoDocumento!=null?idTipoDocumento:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(CULExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return (CULgetListadoDocumentosNoRevisadosResponse)getResult(CULgetListadoDocumentosNoRevisadosResponse.class,__result,"getListadoDocumentosNoRevisadosResponse",__envelope);
            }
        },"urn:getListadoDocumentosNoRevisados");
    }
    
    public android.os.AsyncTask< Void, Void, CULOperationResult< CULgetListadoDocumentosNoRevisadosResponse>> getListadoDocumentosNoRevisadosAsync(final Integer codAplicacion,final Integer idEmpresa,final String nroDocumentoIdentificacion,final String idTipoDocumento)
    {
        return executeAsync(new CULFunctions.IFunc< CULgetListadoDocumentosNoRevisadosResponse>() {
            public CULgetListadoDocumentosNoRevisadosResponse Func() throws Exception {
                return getListadoDocumentosNoRevisados( codAplicacion,idEmpresa,nroDocumentoIdentificacion,idTipoDocumento);
            }
        });
    }
    
    public CULUsuarioDatos getUsuarioLogin(final Integer codAplicacion,final Integer idEmpresa,final String usuario,final String clave,final String ip ) throws Exception
    {
        return (CULUsuarioDatos)execute(new CULIWcfMethod()
        {
            @Override
            public CULExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              CULExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://wsdocuservutil.gmd.com.pe", "getUsuarioLogin");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="codAplicacion";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(codAplicacion);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="idEmpresa";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(idEmpresa);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="usuario";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(usuario!=null?usuario:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="clave";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(clave!=null?clave:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="ip";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(ip!=null?ip:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(CULExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return (CULUsuarioDatos)getResult(CULUsuarioDatos.class,__result,"return",__envelope);
            }
        },"urn:getUsuarioLogin");
    }
    
    public android.os.AsyncTask< Void, Void, CULOperationResult< CULUsuarioDatos>> getUsuarioLoginAsync(final Integer codAplicacion,final Integer idEmpresa,final String usuario,final String clave,final String ip)
    {
        return executeAsync(new CULFunctions.IFunc< CULUsuarioDatos>() {
            public CULUsuarioDatos Func() throws Exception {
                return getUsuarioLogin( codAplicacion,idEmpresa,usuario,clave,ip);
            }
        });
    }
    
    public CULgetListadoDocumentosResponse getListadoDocumentos(final Integer codAplicacion,final Integer idEmpresa,final String nroDocumentoIdentificacion,final String idTipoDocumento ) throws Exception
    {
        return (CULgetListadoDocumentosResponse)execute(new CULIWcfMethod()
        {
            @Override
            public CULExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              CULExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://wsdocuservutil.gmd.com.pe", "getListadoDocumentos");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="codAplicacion";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(codAplicacion);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="idEmpresa";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(idEmpresa);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="nroDocumentoIdentificacion";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(nroDocumentoIdentificacion!=null?nroDocumentoIdentificacion:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="idTipoDocumento";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(idTipoDocumento!=null?idTipoDocumento:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(CULExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return (CULgetListadoDocumentosResponse)getResult(CULgetListadoDocumentosResponse.class,__result,"getListadoDocumentosResponse",__envelope);
            }
        },"urn:getListadoDocumentos");
    }
    
    public android.os.AsyncTask< Void, Void, CULOperationResult< CULgetListadoDocumentosResponse>> getListadoDocumentosAsync(final Integer codAplicacion,final Integer idEmpresa,final String nroDocumentoIdentificacion,final String idTipoDocumento)
    {
        return executeAsync(new CULFunctions.IFunc< CULgetListadoDocumentosResponse>() {
            public CULgetListadoDocumentosResponse Func() throws Exception {
                return getListadoDocumentos( codAplicacion,idEmpresa,nroDocumentoIdentificacion,idTipoDocumento);
            }
        });
    }
    
    public void processInjectionBasedOnServletContext(final String target,final String servletContext ) throws Exception
    {
        execute(new CULIWcfMethod()
        {
            @Override
            public CULExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              CULExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://wsdocuservutil.gmd.com.pe", "processInjectionBasedOnServletContext");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="target";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(target!=null?target:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="servletContext";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(servletContext!=null?servletContext:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(CULExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return null;
            }
        },"urn:processInjectionBasedOnServletContext");
    }
    
    public android.os.AsyncTask< Void, Void, CULOperationResult< Void>> processInjectionBasedOnServletContextAsync(final String target,final String servletContext)
    {
        return executeAsync(new CULFunctions.IFunc< Void>()
        {
            @Override
            public Void Func() throws Exception {
                processInjectionBasedOnServletContext( target,servletContext);
                return null;
            }
        }) ;
    }
    
    public String getCambioClave(final String codAplicacion,final String idEmpresa,final String nomUsuario,final String clave,final String nuevaClave ) throws Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, CULOperationResult< String>> getCambioClaveAsync(final String codAplicacion,final String idEmpresa,final String nomUsuario,final String clave,final String nuevaClave)
    {
        return executeAsync(new CULFunctions.IFunc< String>() {
            public String Func() throws Exception {
                return getCambioClave( codAplicacion,idEmpresa,nomUsuario,clave,nuevaClave);
            }
        });
    }
    
    public String obtenerPdf(final String sPeriodo,final String nTipoDocumento,final String nCodAplicacion,final String sDniUsuario,final String clave,final String nIdeEmpresa,final String sIpUsuario ) throws Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, CULOperationResult< String>> obtenerPdfAsync(final String sPeriodo,final String nTipoDocumento,final String nCodAplicacion,final String sDniUsuario,final String clave,final String nIdeEmpresa,final String sIpUsuario)
    {
        return executeAsync(new CULFunctions.IFunc< String>() {
            public String Func() throws Exception {
                return obtenerPdf( sPeriodo,nTipoDocumento,nCodAplicacion,sDniUsuario,clave,nIdeEmpresa,sIpUsuario);
            }
        });
    }
    
    public void processInjectionBasedOnCurrentContext(final String target ) throws Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    }
    
    public android.os.AsyncTask< Void, Void, CULOperationResult< Void>> processInjectionBasedOnCurrentContextAsync(final String target)
    {
        return executeAsync(new CULFunctions.IFunc< Void>()
        {
            @Override
            public Void Func() throws Exception {
                processInjectionBasedOnCurrentContext( target);
                return null;
            }
        }) ;
    }

    
    protected Object execute(CULIWcfMethod wcfMethod,String methodName) throws Exception
    {
        Transport __httpTransport=createTransport();
        __httpTransport.debug=enableLogging;
        CULExtendedSoapSerializationEnvelope __envelope=wcfMethod.CreateSoapEnvelope();
        try
        {
            sendRequest(methodName, __envelope, __httpTransport);
            
        }
        finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    android.util.Log.i("requestDump",__httpTransport.requestDump);    
                    
                }
                if (__httpTransport.responseDump != null) {
                    android.util.Log.i("responseDump",__httpTransport.responseDump);
                }
            }
        }
        Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault){
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault)__retObj;
            throw convertToException(__fault,__envelope);
        }else{
            return wcfMethod.ProcessResult(__envelope,__retObj);
        }
    }
    
    protected < T> android.os.AsyncTask< Void, Void, CULOperationResult< T>>  executeAsync(final CULFunctions.IFunc< T> func)
    {
        return new android.os.AsyncTask< Void, Void, CULOperationResult< T>>()
        {
            @Override
            protected void onPreExecute() {
                callback.Starting();
            };
            @Override
            protected CULOperationResult< T> doInBackground(Void... params) {
                CULOperationResult< T> result = new CULOperationResult< T>();
                try
                {
                    result.Result= func.Func();
                }
                catch(Exception ex)
                {
                    ex.printStackTrace();
                    result.Exception=ex;
                }
                return result;
            }
            
            @Override
            protected void onPostExecute(CULOperationResult< T> result)
            {
                callback.Completed(result);
            }
        }.execute();
    }
        
    Exception convertToException(org.ksoap2.SoapFault fault,CULExtendedSoapSerializationEnvelope envelope)
    {

        return new Exception(fault.faultstring);
    }
}


