package com.tincio.visualizarboletas.data.services;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.3
//
// Created by Quasar Development at 24/10/2016
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class JHADocumentoWS extends AttributeContainer implements KvmSerializable
{

    
    public String bytesAcuse;
    
    public String bytesDocumento;
    
    public String descripcion;
    
    public String fileName;
    
    public Boolean resultado;

    public JHADocumentoWS ()
    {
    }

    public JHADocumentoWS (Object paramObj,WRHExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                Object obj = info.getValue();
                if (info.name.equals("bytesAcuse"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.bytesAcuse = j.toString();
                            }
                        }
                        else{
                            this.bytesAcuse = obj.toString();
                        }
                    }
                    continue;
            }
                if (info.name.equals("bytesDocumento"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.bytesDocumento = j.toString();
                            }
                        }
                        else{
                            this.bytesDocumento = obj.toString();
                        }
                    }
                    continue;
                }
                if (info.name.equals("descripcion"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.descripcion = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.descripcion = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("fileName"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.fileName = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.fileName = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("resultado"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.resultado = new Boolean(j.toString());
                            }
                        }
                        else if (obj instanceof Boolean){
                            this.resultado = (Boolean)obj;
                        }
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.bytesAcuse!=null?this.bytesAcuse:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.bytesDocumento!=null?this.bytesDocumento:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.descripcion!=null?this.descripcion:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.fileName!=null?this.fileName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.resultado!=null?this.resultado:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 5;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "bytesAcuse";
            info.namespace= "http://xsd.bean.wsdocuservici.gmd.com.pe/xsd";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "bytesDocumento";
            info.namespace= "http://xsd.bean.wsdocuservici.gmd.com.pe/xsd";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "descripcion";
            info.namespace= "http://xsd.bean.wsdocuservici.gmd.com.pe/xsd";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "fileName";
            info.namespace= "http://xsd.bean.wsdocuservici.gmd.com.pe/xsd";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "resultado";
            info.namespace= "http://xsd.bean.wsdocuservici.gmd.com.pe/xsd";
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}

