package com.tincio.visualizarboletas.data.services;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.2
//
// Created by Quasar Development at 11/10/2016
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class WRHDocumentoProceso extends WRHBAuditoria implements KvmSerializable
{

    
    public String deTermCreaAcuse;
    
    public WRHDocumento documento;
    
    public Integer estadoRegenerado;
    
    public String fecVisCuse;
    
    public String fecVisDoc;
    
    public Integer idDocumentoEstado;
    
    public Long idProceso;
    
    public Long idTipoProceso;
    
    public String nombreDocumento;
    
    public String url;
    
    public String urlAcuse;

    public WRHDocumentoProceso ()
    {
    }

    public WRHDocumentoProceso (Object paramObj,WRHExtendedSoapSerializationEnvelope __envelope)
    {
	    super(paramObj, __envelope);
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                Object obj = info.getValue();
                if (info.name.equals("deTermCreaAcuse"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.deTermCreaAcuse = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.deTermCreaAcuse = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("documento"))
                {
                    if(obj!=null)
                    {
                        Object j = obj;
                        this.documento = (WRHDocumento)__envelope.get(j,WRHDocumento.class,false);
                    }
                    continue;
                }
                if (info.name.equals("estadoRegenerado"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.estadoRegenerado = Integer.parseInt(j.toString());
                            }
                        }
                        else if (obj instanceof Integer){
                            this.estadoRegenerado = (Integer)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("fecVisCuse"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.fecVisCuse = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.fecVisCuse = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("fecVisDoc"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.fecVisDoc = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.fecVisDoc = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("idDocumentoEstado"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.idDocumentoEstado = Integer.parseInt(j.toString());
                            }
                        }
                        else if (obj instanceof Integer){
                            this.idDocumentoEstado = (Integer)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("idProceso"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.idProceso = new Long(j.toString());
                            }
                        }
                        else if (obj instanceof Long){
                            this.idProceso = (Long)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("idTipoProceso"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.idTipoProceso = new Long(j.toString());
                            }
                        }
                        else if (obj instanceof Long){
                            this.idTipoProceso = (Long)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("nombreDocumento"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.nombreDocumento = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.nombreDocumento = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("url"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.url = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.url = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("urlAcuse"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.urlAcuse = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.urlAcuse = (String)obj;
                        }
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==count+0)
        {
            return this.deTermCreaAcuse!=null?this.deTermCreaAcuse:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+1)
        {
            return this.documento!=null?this.documento:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+2)
        {
            return this.estadoRegenerado!=null?this.estadoRegenerado:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+3)
        {
            return this.fecVisCuse!=null?this.fecVisCuse:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+4)
        {
            return this.fecVisDoc!=null?this.fecVisDoc:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+5)
        {
            return this.idDocumentoEstado!=null?this.idDocumentoEstado:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+6)
        {
            return this.idProceso!=null?this.idProceso:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+7)
        {
            return this.idTipoProceso!=null?this.idTipoProceso:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+8)
        {
            return this.nombreDocumento!=null?this.nombreDocumento:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+9)
        {
            return this.url!=null?this.url:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+10)
        {
            return this.urlAcuse!=null?this.urlAcuse:SoapPrimitive.NullSkip;
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+11;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        int count = super.getPropertyCount();
        if(propertyIndex==count+0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "deTermCreaAcuse";
            info.namespace= "http://entity.sibe.gmd.com.pe/xsd";
        }
        if(propertyIndex==count+1)
        {
            info.type = WRHDocumento.class;
            info.name = "documento";
            info.namespace= "http://entity.sibe.gmd.com.pe/xsd";
        }
        if(propertyIndex==count+2)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "estadoRegenerado";
            info.namespace= "http://entity.sibe.gmd.com.pe/xsd";
        }
        if(propertyIndex==count+3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "fecVisCuse";
            info.namespace= "http://entity.sibe.gmd.com.pe/xsd";
        }
        if(propertyIndex==count+4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "fecVisDoc";
            info.namespace= "http://entity.sibe.gmd.com.pe/xsd";
        }
        if(propertyIndex==count+5)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "idDocumentoEstado";
            info.namespace= "http://entity.sibe.gmd.com.pe/xsd";
        }
        if(propertyIndex==count+6)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "idProceso";
            info.namespace= "http://entity.sibe.gmd.com.pe/xsd";
        }
        if(propertyIndex==count+7)
        {
            info.type = PropertyInfo.LONG_CLASS;
            info.name = "idTipoProceso";
            info.namespace= "http://entity.sibe.gmd.com.pe/xsd";
        }
        if(propertyIndex==count+8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "nombreDocumento";
            info.namespace= "http://entity.sibe.gmd.com.pe/xsd";
        }
        if(propertyIndex==count+9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "url";
            info.namespace= "http://entity.sibe.gmd.com.pe/xsd";
        }
        if(propertyIndex==count+10)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "urlAcuse";
            info.namespace= "http://entity.sibe.gmd.com.pe/xsd";
        }
        super.getPropertyInfo(propertyIndex,arg1,info);
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}

