package com.tincio.visualizarboletas.data.services;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.2
//
// Created by Quasar Development at 11/10/2016
//
//---------------------------------------------------



public interface WRHIServiceEvents
{
    public void Starting();
    public void Completed(WRHOperationResult result);
}
