package com.tincio.visualizarboletas.data.services;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.2
//
// Created by Quasar Development at 11/10/2016
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class WRHUsuarioDatos extends AttributeContainer implements KvmSerializable
{

    
    public Boolean resultado;
    
    public String sDescripcion;
    
    public String sNombres;
    
    public String ubicacion;

    public WRHUsuarioDatos ()
    {
    }

    public WRHUsuarioDatos (Object paramObj,WRHExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                Object obj = info.getValue();
                if (info.name.equals("resultado"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.resultado = new Boolean(j.toString());
                            }
                        }
                        else if (obj instanceof Boolean){
                            this.resultado = (Boolean)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("sDescripcion"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.sDescripcion = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.sDescripcion = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("sNombres"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.sNombres = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.sNombres = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("ubicacion"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.ubicacion = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.ubicacion = (String)obj;
                        }
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.resultado!=null?this.resultado:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.sDescripcion!=null?this.sDescripcion:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.sNombres!=null?this.sNombres:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.ubicacion!=null?this.ubicacion:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 4;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "resultado";
            info.namespace= "http://xsd.bean.wsdocuservici.gmd.com.pe/xsd";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "sDescripcion";
            info.namespace= "http://xsd.bean.wsdocuservici.gmd.com.pe/xsd";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "sNombres";
            info.namespace= "http://xsd.bean.wsdocuservici.gmd.com.pe/xsd";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ubicacion";
            info.namespace= "http://xsd.bean.wsdocuservici.gmd.com.pe/xsd";
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}

