package com.tincio.visualizarboletas.data.services;




//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.2
//
// Created by Quasar Development at 11/10/2016
//
//---------------------------------------------------


import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;
import org.ksoap2.transport.HttpTransportSE;
import org.ksoap2.transport.HttpsTransportSE;
import org.ksoap2.transport.Transport;

import java.util.List;


public class WRHWSAutenticacionSoap11Binding
{
    interface WRHIWcfMethod
    {
        WRHExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws Exception;

        Object ProcessResult(WRHExtendedSoapSerializationEnvelope __envelope, Object result) throws Exception;
    }

    String url="https://gsd.gmd.com.pe/wsDocuServicesMobile/services/WSAutenticacion.WSAutenticacionHttpSoap11Endpoint/";

    int timeOut=60000;
    public List< HeaderProperty> httpHeaders;
    public boolean enableLogging;

    WRHIServiceEvents callback;
    public WRHWSAutenticacionSoap11Binding(){}

    public WRHWSAutenticacionSoap11Binding (WRHIServiceEvents callback)
    {
        this.callback = callback;
    }
    public WRHWSAutenticacionSoap11Binding(WRHIServiceEvents callback,String url)
    {
        this.callback = callback;
        this.url = url;
    }

    public WRHWSAutenticacionSoap11Binding(WRHIServiceEvents callback,String url,int timeOut)
    {
        this.callback = callback;
        this.url = url;
        this.timeOut=timeOut;
    }

    protected Transport createTransport()
    {
        try
        {
            java.net.URI uri = new java.net.URI(url);
            if(uri.getScheme().equalsIgnoreCase("https"))
            {
                int port=uri.getPort()>0?uri.getPort():443;
                return new HttpsTransportSE(uri.getHost(), port, uri.getPath(), timeOut);
            }
            else
            {
                return new HttpTransportSE(url,timeOut);
            }

        }
        catch (java.net.URISyntaxException e)
        {
        }
        return null;
    }
    
    protected WRHExtendedSoapSerializationEnvelope createEnvelope()
    {
        WRHExtendedSoapSerializationEnvelope envelope= new WRHExtendedSoapSerializationEnvelope(WRHExtendedSoapSerializationEnvelope.VER11);
        return envelope;
    }
    
    protected List sendRequest(String methodName,WRHExtendedSoapSerializationEnvelope envelope,Transport transport  )throws Exception
    {
        return transport.call(methodName, envelope, httpHeaders);
    }

    Object getResult(Class destObj,Object source,String resultName,WRHExtendedSoapSerializationEnvelope __envelope) throws Exception
    {
        if(source==null)
        {
            return null;
        }
        if(source instanceof SoapPrimitive)
        {
            SoapPrimitive soap =(SoapPrimitive)source;
            if(soap.getName().equals(resultName))
            {
                Object instance=__envelope.get(source,destObj,false);
                return instance;
            }
        }
        else
        {
            SoapObject soap = (SoapObject)source;
            if (soap.hasProperty(resultName))
            {
                Object j=soap.getProperty(resultName);
                if(j==null)
                {
                    return null;
                }
                Object instance=__envelope.get(j,destObj,false);
                return instance;
            }
            else if( soap.getName().equals(resultName)) {
                Object instance=__envelope.get(source,destObj,false);
                return instance;
            }
       }
       return null;
    }

        
    public WRHgetListadoDocumentosNoRevisadosResponse getListadoDocumentosNoRevisados(final Integer codAplicacion,final Integer idEmpresa,final String nroDocumentoIdentificacion,final String idTipoDocumento ) throws Exception
    {
        return (WRHgetListadoDocumentosNoRevisadosResponse)execute(new WRHIWcfMethod()
        {
            @Override
            public WRHExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              WRHExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://wsdocuservutil.gmd.com.pe", "getListadoDocumentosNoRevisados");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="codAplicacion";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(codAplicacion);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="idEmpresa";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(idEmpresa);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="nroDocumentoIdentificacion";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(nroDocumentoIdentificacion!=null?nroDocumentoIdentificacion:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="idTipoDocumento";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(idTipoDocumento!=null?idTipoDocumento:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(WRHExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return (WRHgetListadoDocumentosNoRevisadosResponse)getResult(WRHgetListadoDocumentosNoRevisadosResponse.class,__result,"getListadoDocumentosNoRevisadosResponse",__envelope);
            }
        },"urn:getListadoDocumentosNoRevisados");
    }
    
    public android.os.AsyncTask< Void, Void, WRHOperationResult< WRHgetListadoDocumentosNoRevisadosResponse>> getListadoDocumentosNoRevisadosAsync(final Integer codAplicacion,final Integer idEmpresa,final String nroDocumentoIdentificacion,final String idTipoDocumento)
    {
        return executeAsync(new WRHFunctions.IFunc< WRHgetListadoDocumentosNoRevisadosResponse>() {
            public WRHgetListadoDocumentosNoRevisadosResponse Func() throws Exception {
                return getListadoDocumentosNoRevisados( codAplicacion,idEmpresa,nroDocumentoIdentificacion,idTipoDocumento);
            }
        });
    }
    
    public WRHgetListadoDocumentosMobileResponse getListadoDocumentosMobile(final Integer idEmpresa,final String nroDocumentoIdentificacion,final String idTipoDocumento,final String periodo ) throws Exception
    {
        return (WRHgetListadoDocumentosMobileResponse)execute(new WRHIWcfMethod()
        {
            @Override
            public WRHExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              WRHExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://wsdocuservutil.gmd.com.pe", "getListadoDocumentosMobile");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="idEmpresa";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(idEmpresa);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="nroDocumentoIdentificacion";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(nroDocumentoIdentificacion!=null?nroDocumentoIdentificacion:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="idTipoDocumento";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(idTipoDocumento!=null?idTipoDocumento:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="periodo";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(periodo!=null?periodo:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(WRHExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return (WRHgetListadoDocumentosMobileResponse)getResult(WRHgetListadoDocumentosMobileResponse.class,__result,"getListadoDocumentosMobileResponse",__envelope);
            }
        },"urn:getListadoDocumentosMobile");
    }
    
    public android.os.AsyncTask< Void, Void, WRHOperationResult< WRHgetListadoDocumentosMobileResponse>> getListadoDocumentosMobileAsync(final Integer idEmpresa,final String nroDocumentoIdentificacion,final String idTipoDocumento,final String periodo)
    {
        return executeAsync(new WRHFunctions.IFunc< WRHgetListadoDocumentosMobileResponse>() {
            public WRHgetListadoDocumentosMobileResponse Func() throws Exception {
                return getListadoDocumentosMobile( idEmpresa,nroDocumentoIdentificacion,idTipoDocumento,periodo);
            }
        });
    }
    
    public WRHUsuarioDatos getUsuarioLogin(final Integer codAplicacion,final Integer idEmpresa,final String usuario,final String clave,final String ip,final String keyios,final String keyandroid ) throws Exception
    {
        return (WRHUsuarioDatos)execute(new WRHIWcfMethod()
        {
            @Override
            public WRHExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              WRHExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://wsdocuservutil.gmd.com.pe", "getUsuarioLogin");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="codAplicacion";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(codAplicacion);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="idEmpresa";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(idEmpresa);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="usuario";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(usuario!=null?usuario:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="clave";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(clave!=null?clave:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="ip";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(ip!=null?ip:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="keyios";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(keyios!=null?keyios:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="keyandroid";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(keyandroid!=null?keyandroid:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(WRHExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return (WRHUsuarioDatos)getResult(WRHUsuarioDatos.class,__result,"return",__envelope);
            }
        },"urn:getUsuarioLogin");
    }
    
    public android.os.AsyncTask< Void, Void, WRHOperationResult< WRHUsuarioDatos>> getUsuarioLoginAsync(final Integer codAplicacion,final Integer idEmpresa,final String usuario,final String clave,final String ip,final String keyios,final String keyandroid)
    {
        return executeAsync(new WRHFunctions.IFunc< WRHUsuarioDatos>() {
            public WRHUsuarioDatos Func() throws Exception {
                return getUsuarioLogin( codAplicacion,idEmpresa,usuario,clave,ip,keyios,keyandroid);
            }
        });
    }
    
    public WRHgetListadoDocumentosResponse getListadoDocumentos(final Integer codAplicacion,final Integer idEmpresa,final String nroDocumentoIdentificacion,final String idTipoDocumento ) throws Exception
    {
        return (WRHgetListadoDocumentosResponse)execute(new WRHIWcfMethod()
        {
            @Override
            public WRHExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              WRHExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://wsdocuservutil.gmd.com.pe", "getListadoDocumentos");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="codAplicacion";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(codAplicacion);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="idEmpresa";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(idEmpresa);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="nroDocumentoIdentificacion";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(nroDocumentoIdentificacion!=null?nroDocumentoIdentificacion:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="idTipoDocumento";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(idTipoDocumento!=null?idTipoDocumento:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(WRHExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return (WRHgetListadoDocumentosResponse)getResult(WRHgetListadoDocumentosResponse.class,__result,"getListadoDocumentosResponse",__envelope);
            }
        },"urn:getListadoDocumentos");
    }
    
    public android.os.AsyncTask< Void, Void, WRHOperationResult< WRHgetListadoDocumentosResponse>> getListadoDocumentosAsync(final Integer codAplicacion,final Integer idEmpresa,final String nroDocumentoIdentificacion,final String idTipoDocumento)
    {
        return executeAsync(new WRHFunctions.IFunc< WRHgetListadoDocumentosResponse>() {
            public WRHgetListadoDocumentosResponse Func() throws Exception {
                return getListadoDocumentos( codAplicacion,idEmpresa,nroDocumentoIdentificacion,idTipoDocumento);
            }
        });
    }
    
    public void processInjectionBasedOnServletContext(final String target,final String servletContext ) throws Exception
    {
        execute(new WRHIWcfMethod()
        {
            @Override
            public WRHExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              WRHExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://wsdocuservutil.gmd.com.pe", "processInjectionBasedOnServletContext");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="target";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(target!=null?target:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="servletContext";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(servletContext!=null?servletContext:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(WRHExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return null;
            }
        },"urn:processInjectionBasedOnServletContext");
    }
    
    public android.os.AsyncTask< Void, Void, WRHOperationResult< Void>> processInjectionBasedOnServletContextAsync(final String target,final String servletContext)
    {
        return executeAsync(new WRHFunctions.IFunc< Void>()
        {
            @Override
            public Void Func() throws Exception {
                processInjectionBasedOnServletContext( target,servletContext);
                return null;
            }
        }) ;
    }

    interface WWOIWcfMethod
    {
        WRHExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws Exception;

        Object ProcessResult(WRHExtendedSoapSerializationEnvelope __envelope, Object result) throws Exception;
    }

    public WWOUsuarioClave getCambioClave(final String codAplicacion,final String idEmpresa,final String nomUsuario,final String clave,final String nuevaClave ) throws Exception
    {
        return (WWOUsuarioClave)execute(new WRHIWcfMethod()
        {
            @Override
            public WRHExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                WRHExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://wsdocuservutil.gmd.com.pe", "getCambioClave");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="codAplicacion";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(codAplicacion);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="idEmpresa";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(idEmpresa);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="nomUsuario";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(nomUsuario!=null?nomUsuario:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="clave";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(clave!=null?clave:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="nuevaClave";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(nuevaClave!=null?nuevaClave:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public Object ProcessResult(WRHExtendedSoapSerializationEnvelope __envelope, Object result) throws Exception {
                return (WWOUsuarioClave)getResult(WWOUsuarioClave.class,result,"return",__envelope);
            }

        },"urn:getCambioClave");
    }

    public android.os.AsyncTask< Void, Void, WRHOperationResult< WWOUsuarioClave>> getCambioClaveAsync(final String codAplicacion,final String idEmpresa,final String nomUsuario,final String clave,final String nuevaClave)
    {
        return executeAsync(new WRHFunctions.IFunc< WWOUsuarioClave>() {
            public WWOUsuarioClave Func() throws Exception {
                return getCambioClave( codAplicacion,idEmpresa,nomUsuario,clave,nuevaClave);
            }
        });
    }
    
    /*public String obtenerPdf(final String sPeriodo,final String nTipoDocumento,final String nCodAplicacion,final String sDniUsuario,final String clave,final String nIdeEmpresa,final String sIpUsuario ) throws Exception
    {
       return null;
    }
    
    public android.os.AsyncTask< Void, Void, WRHOperationResult< String>> obtenerPdfAsync(final String sPeriodo,final String nTipoDocumento,final String nCodAplicacion,final String sDniUsuario,final String clave,final String nIdeEmpresa,final String sIpUsuario)
    {
        return executeAsync(new WRHFunctions.IFunc< String>() {
            public String Func() throws Exception {
                return obtenerPdf( sPeriodo,nTipoDocumento,nCodAplicacion,sDniUsuario,clave,nIdeEmpresa,sIpUsuario);
            }
        });
    }*/
    
    public void processInjectionBasedOnCurrentContext(final String target ) throws Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    }
    
    public android.os.AsyncTask< Void, Void, WRHOperationResult< Void>> processInjectionBasedOnCurrentContextAsync(final String target)
    {
        return executeAsync(new WRHFunctions.IFunc< Void>()
        {
            @Override
            public Void Func() throws Exception {
                processInjectionBasedOnCurrentContext( target);
                return null;
            }
        }) ;
    }
    
    public WWOEmpresa getEmpresas( ) throws Exception
    {
        return (WWOEmpresa)execute(new WRHIWcfMethod()
        {
            @Override
            public WRHExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                WRHExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://wsdocuservutil.gmd.com.pe", "getEmpresas");
                __envelope.setOutputSoapObject(__soapReq);

                return __envelope;
            }

            @Override
            public Object ProcessResult(WRHExtendedSoapSerializationEnvelope __envelope, Object result) throws Exception {
                return (WWOEmpresa)getResult(WWOEmpresa.class,result,"return",__envelope);
            }
        },"urn:getEmpresas");
    }
    
    public android.os.AsyncTask< Void, Void, WRHOperationResult< WWOEmpresa>> getEmpresasAsync()
    {
        return executeAsync(new WRHFunctions.IFunc< WWOEmpresa>() {
            public WWOEmpresa Func() throws Exception {
                return getEmpresas( );
            }
        });
    }

    
    protected Object execute(WRHIWcfMethod wcfMethod,String methodName) throws Exception
    {
        Transport __httpTransport=createTransport();
        __httpTransport.debug=enableLogging;
        WRHExtendedSoapSerializationEnvelope __envelope=wcfMethod.CreateSoapEnvelope();
        try
        {
            sendRequest(methodName, __envelope, __httpTransport);
            
        }
        finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    android.util.Log.i("requestDump",__httpTransport.requestDump);    
                    
                }
                if (__httpTransport.responseDump != null) {
                    android.util.Log.i("responseDump",__httpTransport.responseDump);
                }
            }
        }
        Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault){
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault)__retObj;
            throw convertToException(__fault,__envelope);
        }else{
            return wcfMethod.ProcessResult(__envelope,__retObj);
        }
    }
    
    protected < T> android.os.AsyncTask< Void, Void, WRHOperationResult< T>>  executeAsync(final WRHFunctions.IFunc< T> func)
    {
        return new android.os.AsyncTask< Void, Void, WRHOperationResult< T>>()
        {
            @Override
            protected void onPreExecute() {
                callback.Starting();
            };
            @Override
            protected WRHOperationResult< T> doInBackground(Void... params) {
                WRHOperationResult< T> result = new WRHOperationResult< T>();
                try
                {
                    result.Result= func.Func();
                }
                catch(Exception ex)
                {
                    ex.printStackTrace();
                    result.Exception=ex;
                }
                return result;
            }
            
            @Override
            protected void onPostExecute(WRHOperationResult< T> result)
            {
                callback.Completed(result);
            }
        }.execute();
    }
        
    Exception convertToException(org.ksoap2.SoapFault fault,WRHExtendedSoapSerializationEnvelope envelope)
    {

        return new Exception(fault.faultstring);
    }
    ////get obtener pdf

    public JHADocumentoWS obtenerPdf(final String sPeriodo,final Integer nTipoDocumento,final Integer nCodAplicacion,final String sDniUsuario,final String clave,final Integer nIdeEmpresa,final String sIpUsuario ) throws java.lang.Exception
    {
        return (JHADocumentoWS)execute(new WRHIWcfMethod()
        {
            @Override
            public WRHExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                WRHExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://wsdocuservutil.gmd.com.pe", "obtenerPdf");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="sPeriodo";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(sPeriodo!=null?sPeriodo:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="nTipoDocumento";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(nTipoDocumento);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="nCodAplicacion";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(nCodAplicacion);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="sDniUsuario";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(sDniUsuario!=null?sDniUsuario:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="clave";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(clave!=null?clave:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="nIdeEmpresa";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(nIdeEmpresa);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://wsdocuservutil.gmd.com.pe";
                __info.name="sIpUsuario";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(sIpUsuario!=null?sIpUsuario:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(WRHExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (JHADocumentoWS)getResult(JHADocumentoWS.class,__result,"return",__envelope);
            }
        },"urn:obtenerPdf");
    }

    public android.os.AsyncTask< Void, Void, WRHOperationResult< JHADocumentoWS>> obtenerPdfAsync(final String sPeriodo,final Integer nTipoDocumento,final Integer nCodAplicacion,final String sDniUsuario,final String clave,final Integer nIdeEmpresa,final String sIpUsuario)
    {
        return executeAsync(new WRHFunctions.IFunc< JHADocumentoWS>() {
            public JHADocumentoWS Func() throws java.lang.Exception {
                return obtenerPdf( sPeriodo,nTipoDocumento,nCodAplicacion,sDniUsuario,clave,nIdeEmpresa,sIpUsuario);
            }
        });
    }

}


